### ISSUE TITLE
Magic numbers are anti-pattern.

### ISSUE THREAD

**Issue by einarhorn** [yan-h/midi_lattice#2]
https://github.com/yan-h/midi_lattice/blob/b4c20c220bc86052bc068f65f601009bb81ec9cf/src/lib.rs#L99C43-L99C44

Please read up on this first before putting your code out to the world: https://en.wikipedia.org/wiki/Magic_number_(programming)#:~:text=In%20computer%20programming%2C%20a%20magic,see%20List%20of%20file%20signatures

**Comment by yan-h** [comment]
It's ok there's no such thing as magic
